version: '3.8'
services:
  sqlite3:
    container_name: 'explorer_db'
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db
  juno:
    container_name: 'juno_mainnet'
    image: nethermind/juno
    ports:
        - 6060:6060
    volumes:
      - ./juno_files/:/var/lib/juno
    command: >
      --pending-poll-interval "60s"
      --http-port 6060
      --db-path /var/lib/juno
      --eth-node "${ETH_NODE_URL}"
      --network mainnet

networks:
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  pgadmin_data:

