version: '3.8'

services:
  starknet-explorer:
    build: .
    ports:
      - "4000:4000"
    environment:
      - RPC_API_HOST=http://host.docker.internal:9944
      - DATABASE_URL=ecto://postgres:postgres@host.docker.internal:5432/starknet_explorer_dev
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - explorer

  postgres:
    container_name: starknet_explorer_dev_db
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starknet_explorer_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres

  pgadmin:
    container_name: 'starknet_explorer_pgadmin_service'
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=lambda@email.com
        - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
        - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      default:
        aliases:
          - pgadmin
networks:
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data:

