version: '3.8'

services:
  postgres:
    container_name: starknet_explorer_dev_db
    image: postgres:15.3
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starknet_explorer_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres

  pgadmin:
    container_name: 'starknet_explorer_pgadmin_service'
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=lambda@email.com
        - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
        - 127.0.0.1:5050:80
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
    networks:
      default:
        aliases:
          - pgadmin
networks:
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  pgadmin_data:

