version: '3.8'
services:
  juno:
    container_name: 'juno_mainnet'
    image: nethermind/juno
    ports:
        - 6060:6060
    volumes:
      - ./juno_files/:/var/lib/juno
    command: >
      --pending-poll-interval "60s"
      --http-port 6060
      --db-path /var/lib/juno
      --eth-node "${ETH_NODE_URL}"
      --network mainnet
  postgres:
    container_name: madaraexplorer_db
    image: postgres:14.6
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=madaraexplorer_user
      - POSTGRES_PASSWORD=madaraexplorerlambda
      - POSTGRES_DB=madaraexplorer_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data/

networks:
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  pgadmin_data:

